# Generated by Django 3.1.1 on 2020-09-12 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_auto_20200912_2141'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityWard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelatedWardForMunicipality', to='location.municipality')),
            ],
            options={
                'verbose_name_plural': 'Municipality Wards',
            },
        ),
        migrations.CreateModel(
            name='VDCWard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vdc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RelatedWardForVDC', to='location.vdc')),
            ],
            options={
                'verbose_name_plural': 'VDC Wards',
            },
        ),
        migrations.RemoveField(
            model_name='vdcwardnumber',
            name='vdc',
        ),
        migrations.DeleteModel(
            name='MunicipalityWardNumber',
        ),
        migrations.DeleteModel(
            name='VDCWardNumber',
        ),
    ]
