# Generated by Django 3.1.3 on 2021-04-11 07:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_medias', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploaded_medias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('approve_media', 'Can toggle approval status of media')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multimedia.media')),
                ('is_approved', models.BooleanField(default=False)),
            ],
            bases=('multimedia.media',),
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multimedia.media')),
                ('is_approved', models.BooleanField(default=False)),
            ],
            bases=('multimedia.media',),
        ),
        migrations.CreateModel(
            name='MultimediaVideoUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(unique=True)),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_urls', to='multimedia.multimedia')),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(unique=True, upload_to='multimedia/videos', validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv'])], verbose_name='Multimedia Video File')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_video', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Multimedia Videos',
            },
        ),
        migrations.CreateModel(
            name='MultimediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='multimedia/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])])),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_image', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Multimedia Images',
            },
        ),
        migrations.CreateModel(
            name='MultimediaAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(unique=True, upload_to='multimedia/audios', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])], verbose_name='Multimedia Audio File')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_audio', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Multimedia Audios',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommentReplies', to='multimedia.comment')),
                ('writer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='multimedia.article')),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_comments', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to='multimedia.article')),
            ],
            options={
                'verbose_name': 'Article Images',
            },
        ),
        migrations.CreateModel(
            name='PinMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pinner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_medias', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_articles', to='multimedia.article')),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pinned_multimedias', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name_plural': 'Pinned Medias',
                'unique_together': {('article', 'pinner'), ('multimedia', 'pinner')},
            },
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lover', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='loved_medias', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loved_articles', to='multimedia.article')),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loved_multimedias', to='multimedia.multimedia')),
            ],
            options={
                'unique_together': {('article', 'lover'), ('multimedia', 'lover')},
            },
        ),
        migrations.CreateModel(
            name='BookmarkMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('marker', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_medias', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_articles', to='multimedia.article')),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_multimedias', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name_plural': 'Media Bookmarks',
                'unique_together': {('article', 'marker'), ('multimedia', 'marker')},
            },
        ),
    ]
