# Generated by Django 3.1.3 on 2020-11-28 14:21

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MultimediaApprover', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MediaUploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multimedia.media')),
                ('is_approved', models.BooleanField(default=False)),
            ],
            bases=('multimedia.media',),
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multimedia.media')),
                ('video_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(unique=True), size=3)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            bases=('multimedia.media',),
        ),
        migrations.CreateModel(
            name='MultimediaVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(unique=True, upload_to='multimedia/videos', validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv'])], verbose_name='Multimedia Video File')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MultimediaVideo', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Multimedia Videos',
            },
        ),
        migrations.CreateModel(
            name='MultimediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='multimedia/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])])),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MultimediaImage', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Multimedia Images',
            },
        ),
        migrations.CreateModel(
            name='MultimediaAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(unique=True, upload_to='multimedia/audios', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])], verbose_name='Multimedia Audio File')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MultimediaAudio', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Multimedia Audios',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommentReplies', to='multimedia.comment')),
                ('writer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='CommentWriter', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArticleComment', to='multimedia.article')),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MultimediaComment', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticleImage', to='multimedia.article')),
            ],
            options={
                'verbose_name': 'Article Images',
            },
        ),
        migrations.CreateModel(
            name='PinMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pinner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='BookmarkPinner', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PinArticle', to='multimedia.article')),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PinMultimedia', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name_plural': 'Pinned Medias',
                'unique_together': {('multimedia', 'pinner'), ('article', 'pinner')},
            },
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lover', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='MediaLover', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LoveArticle', to='multimedia.article')),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LoveMultimedia', to='multimedia.multimedia')),
            ],
            options={
                'unique_together': {('multimedia', 'lover'), ('article', 'lover')},
            },
        ),
        migrations.CreateModel(
            name='BookmarkMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('marker', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='BookmarkActor', to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BookmarkArticle', to='multimedia.article')),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BookmarkMultimedia', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name_plural': 'Media Bookmarks',
                'unique_together': {('multimedia', 'marker'), ('article', 'marker')},
            },
        ),
    ]
