# Generated by Django 3.1.8 on 2021-06-12 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import multimedia.sub_models.media


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('is_pinned', models.BooleanField(default=False, editable=False)),
                ('is_approved', models.BooleanField(default=False, editable=False)),
                ('approved_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_multimedias', to=settings.AUTH_USER_MODEL)),
                ('pinner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pinned_multimedias', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_multimedias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('yt_info', models.JSONField(blank=True, editable=False, null=True)),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_video_urls', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Multimedia Video Url',
                'verbose_name_plural': 'Multimedia Video Urls',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(unique=True, upload_to=multimedia.sub_models.media.upload_video_to, validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv'])], verbose_name='Multimedia Video File')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_videos', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Multimedia Video',
                'verbose_name_plural': 'Multimedia Videos',
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.FileField(unique=True, upload_to=multimedia.sub_models.media.upload_audio_to, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])], verbose_name='Multimedia Audio File')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_sounds', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Multimedia Sound',
                'verbose_name_plural': 'Multimedia Sounds',
            },
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lover', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='my_loves', to=settings.AUTH_USER_MODEL)),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loved', to='multimedia.multimedia')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=multimedia.sub_models.media.upload_image_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])])),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_images', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Multimedia Image',
                'verbose_name_plural': 'Multimedia Images',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='multimedia.multimedia')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='multimedia.comment')),
                ('writer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('marker', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_medias', to=settings.AUTH_USER_MODEL)),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedias', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name_plural': 'Media Bookmarks',
            },
        ),
    ]
