# Generated by Django 3.1.3 on 2021-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediavideourls',
            name='video_url',
            field=models.URLField(),
        ),
    ]
