# Generated by Django 3.1.8 on 2021-06-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videourl',
            name='yt_info',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
