# Generated by Django 3.1.8 on 2021-05-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_approved",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="multimedia",
            name="is_approved",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
