# Generated by Django 3.1 on 2020-08-23 17:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='media',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='multimedia',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='multimedia',
            name='video',
        ),
        migrations.AddField(
            model_name='article',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MultimediaVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='multimedia/videos', validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv'])], verbose_name='Multimedia Video File')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MultimediaVideo', to='multimedia.multimedia')),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='multimedia/audios', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])], verbose_name='Multimedia Audio File')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MultimediaAudio', to='multimedia.multimedia')),
            ],
        ),
    ]
