# Generated by Django 3.1.8 on 2021-05-14 19:05

import django.core.validators
from django.db import migrations, models

import multimedia.models


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleimage",
            name="image",
            field=models.ImageField(
                upload_to=multimedia.models.upload_article_image_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "gif", "bmp", "tiff", "JPG"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="multimediaaudio",
            name="audio",
            field=models.FileField(
                unique=True,
                upload_to=multimedia.models.upload_multimedia_audio_to,
                validators=[
                    django.core.validators.FileExtensionValidator(["mp3", "wav"])
                ],
                verbose_name="Multimedia Audio File",
            ),
        ),
        migrations.AlterField(
            model_name="multimediaimage",
            name="image",
            field=models.ImageField(
                upload_to=multimedia.models.upload_multimedia_image_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "gif", "bmp", "tiff", "JPG"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="multimediavideo",
            name="video",
            field=models.FileField(
                unique=True,
                upload_to=multimedia.models.upload_multimedia_video_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["webm", "mp4", "mpeg", "flv"]
                    )
                ],
                verbose_name="Multimedia Video File",
            ),
        ),
    ]
