# Generated by Django 3.1 on 2020-09-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='multimedia/images')),
                ('multimedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MultimediaImage', to='multimedia.multimedia')),
            ],
        ),
    ]
