# Generated by Django 3.1.1 on 2020-09-12 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('multimedia', '0002_multimediaimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='media',
            unique_together=set(),
        ),
    ]
