# Generated by Django 3.1.8 on 2021-05-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20210515_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Article Image', 'verbose_name_plural': 'Article Images'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='multimediaaudio',
            options={'verbose_name': 'Multimedia Audio', 'verbose_name_plural': 'Multimedia Audios'},
        ),
        migrations.AlterModelOptions(
            name='multimediaimage',
            options={'verbose_name': 'Multimedia Image', 'verbose_name_plural': 'Multimedia Images'},
        ),
        migrations.AlterModelOptions(
            name='multimediavideo',
            options={'verbose_name': 'Multimedia Video', 'verbose_name_plural': 'Multimedia Videos'},
        ),
        migrations.AlterModelOptions(
            name='multimediavideourls',
            options={'verbose_name': 'Multimedia Vide Url', 'verbose_name_plural': 'Multimedia Vide Urls'},
        ),
        migrations.AlterField(
            model_name='multimediaaudio',
            name='multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_audios', to='multimedia.multimedia'),
        ),
        migrations.AlterField(
            model_name='multimediaimage',
            name='multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_images', to='multimedia.multimedia'),
        ),
        migrations.AlterField(
            model_name='multimediavideo',
            name='multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_videos', to='multimedia.multimedia'),
        ),
        migrations.AlterField(
            model_name='multimediavideourls',
            name='multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia_video_urls', to='multimedia.multimedia'),
        ),
    ]
