# Generated by Django 3.1.1 on 2020-09-13 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_auto_20200907_1634'),
        ('multimedia', '0003_auto_20200912_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='ArticleComment', to='multimedia.article')),
                ('multimedia',
                 models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='MultimediaComment', to='multimedia.multimedia')),
                ('writer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='CommentWriter', to='accounts.member')),
            ],
            options={
                'unique_together': {('multimedia', 'writer'), ('article', 'writer')},
            },
        ),
    ]
