# Generated by Django 3.1 on 2020-08-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_auto_20200828_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='approved_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
