# Generated by Django 3.1.1 on 2020-09-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_mediacomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacomment',
            options={'verbose_name_plural': 'Multimedia Comments'},
        ),
        migrations.AlterField(
            model_name='mediacomment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ArticleComment', to='multimedia.article'),
        ),
        migrations.AlterField(
            model_name='mediacomment',
            name='multimedia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MultimediaComment', to='multimedia.multimedia'),
        ),
    ]
