# Generated by Django 3.1.1 on 2020-09-13 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia', '0005_auto_20200913_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacomment',
            name='writer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='CommentWriter', to=settings.AUTH_USER_MODEL),
        ),
    ]
