# Generated by Django 3.1 on 2020-08-30 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0006_auto_20200830_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediaaudio',
            name='audio',
            field=models.FileField(default=0, unique=True, upload_to='multimedia/audios', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])], verbose_name='Multimedia Audio File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multimediavideo',
            name='video',
            field=models.FileField(unique=True, upload_to='multimedia/videos', validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv'])], verbose_name='Multimedia Video File'),
        ),
    ]
