# Generated by Django 3.1.1 on 2020-09-13 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('multimedia', '0007_auto_20200913_1259'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
