# Generated by Django 3.1.1 on 2020-09-13 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0009_auto_20200913_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to='articles', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='multimediaimage',
            name='image',
            field=models.ImageField(upload_to='multimedia/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff'])]),
        ),
    ]
