# Generated by Django 3.1.1 on 2020-09-29 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multimedia', '0010_auto_20200913_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PinArticle', to='multimedia.article')),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PinMultimedia', to='multimedia.multimedia')),
                ('pinner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='BookmarkPinner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('multimedia', 'pinner'), ('article', 'pinner')},
            },
        ),
        migrations.CreateModel(
            name='BookmarkMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BookmarkArticle', to='multimedia.article')),
                ('marker', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='BookmarkActor', to=settings.AUTH_USER_MODEL)),
                ('multimedia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BookmarkMultimedia', to='multimedia.multimedia')),
            ],
            options={
                'unique_together': {('multimedia', 'marker'), ('article', 'marker')},
            },
        ),
    ]
