# Generated by Django 3.1.3 on 2020-11-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0011_bookmarkmedia_pinmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Article Images'},
        ),
        migrations.AlterModelOptions(
            name='bookmarkmedia',
            options={'verbose_name_plural': 'Media Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='multimediaaudio',
            options={'verbose_name': 'Multimedia Audios'},
        ),
        migrations.AlterModelOptions(
            name='multimediaimage',
            options={'verbose_name': 'Multimedia Images'},
        ),
        migrations.AlterModelOptions(
            name='multimediavideo',
            options={'verbose_name': 'Multimedia Videos'},
        ),
        migrations.AlterModelOptions(
            name='pinmedia',
            options={'verbose_name_plural': 'Pinned Medias'},
        ),
    ]
