# Generated by Django 3.1.3 on 2020-11-25 17:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0012_auto_20201124_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='video_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(unique=True), default=[], size=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
