# Generated by Django 3.1.8 on 2021-05-18 21:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='valid nepali phone number', max_length=128, null=True, region=None, unique=True),
        ),
    ]
