# Generated by Django 3.1.8 on 2021-05-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': [('can_approve_member', 'Can toggle Approval Status')], 'verbose_name_plural': 'Members'},
        ),
    ]
