# Generated by Django 3.1.3 on 2020-11-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbranch',
            name='branch_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='memberbranch',
            unique_together={('member', 'branch_id')},
        ),
        migrations.RemoveField(
            model_name='memberbranch',
            name='branch_ids',
        ),
    ]
