# Generated by Django 3.1.8 on 2021-06-23 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers', to='location.municipality'),
        ),
        migrations.AddField(
            model_name='profile',
            name='municipality_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers', to='location.municipalityward'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers', to='location.vdc'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vdc_ward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers', to='location.vdcward'),
        ),
    ]
