# Generated by Django 3.1.8 on 2021-05-19 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210519_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='resetpasswordcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
