# Generated by Django 3.1 on 2020-09-07 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('accounts', '0002_member_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MemberMunicipality', to='location.municipality'),
        ),
        migrations.AddField(
            model_name='member',
            name='vdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MemberVDC', to='location.vdc'),
        ),
    ]
