# Generated by Django 3.1.8 on 2021-06-24 17:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210623_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverimage',
            name='active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Should be a registered Nepal phone number.', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_town',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
