# Generated by Django 3.1 on 2020-08-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200826_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='address',
            new_name='permanent_address',
        ),
        migrations.AddField(
            model_name='member',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MemberProvince', to='accounts.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='temporary_address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MemberCountry', to='accounts.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MemberDistrict', to='accounts.district'),
            preserve_default=False,
        ),
    ]
