# Generated by Django 3.1.8 on 2021-05-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210519_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_role_branch', to='accounts.memberbranch'),
        ),
    ]
