# Generated by Django 3.1.3 on 2020-11-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201128_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberbranch',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='memberrole',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.AlterUniqueTogether(
            name='memberbranch',
            unique_together={('member', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='memberrole',
            unique_together={('member', 'role_name', 'branch')},
        ),
    ]
