# Generated by Django 3.1.8 on 2021-05-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('accounts', '0004_auto_20210522_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_branch', to='branch.branch'),
        ),
    ]
