# Generated by Django 3.1 on 2020-09-07 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_auto_20200907_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='member',
            name='municipality_ward_no',
        ),
        migrations.RemoveField(
            model_name='member',
            name='vdc',
        ),
        migrations.RemoveField(
            model_name='member',
            name='vdc_ward_no',
        ),
    ]
