# Generated by Django 3.1.8 on 2021-05-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210522_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_branch_roles', to='accounts.memberbranch'),
        ),
    ]
