# Generated by Django 3.1 on 2020-09-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_auto_20200907_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default=0, upload_to='branch'),
            preserve_default=False,
        ),
    ]
