# Generated by Django 3.1 on 2020-09-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0006_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='admin_avatar.png', upload_to='branch'),
        ),
    ]
