# Generated by Django 3.1.8 on 2021-05-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210522_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberrole',
            old_name='branch',
            new_name='member_branch',
        ),
        migrations.AlterUniqueTogether(
            name='memberrole',
            unique_together={('member', 'role_name', 'member_branch')},
        ),
    ]
