# Generated by Django 3.1 on 2020-09-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200907_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='admin-avatar.png', upload_to='branch'),
        ),
    ]
