# Generated by Django 3.1.1 on 2020-09-13 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200907_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='admin-avatar.png', upload_to='branch', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='member',
            name='permanent_address',
            field=models.CharField(default='hello', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='temporary_address',
            field=models.CharField(default='hello', max_length=512),
            preserve_default=False,
        ),
    ]
