# Generated by Django 3.1.3 on 2020-11-27 12:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201127_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(unique=True), blank=True, null=True, size=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
