# Generated by Django 3.1.3 on 2020-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201127_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
