# Generated by Django 3.1.3 on 2020-11-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0011_auto_20201123_1732'),
        ('event', '0002_auto_20201123_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventOrganizer', to='branch.branch'),
        ),
    ]
