# Generated by Django 3.1.8 on 2021-05-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210523_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
