# Generated by Django 3.1.3 on 2020-11-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20201123_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact',
        ),
    ]
