# Generated by Django 3.1.3 on 2020-11-23 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(unique=True), default=[555], size=3),
            preserve_default=False,
        ),
    ]
