# Generated by Django 3.1.8 on 2021-05-23 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import event.sub_models.event
import event.sub_models.event_media


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210523_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created_at',), 'permissions': [('approve_event', 'Can toggle approval status of event')]},
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=event.sub_models.event.upload_event_banner_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])]),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(upload_to=event.sub_models.event_media.upload_event_image_to, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])]),
        ),
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=event.sub_models.event_media.upload_event_video_to, validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv'])])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_videos', to='event.event')),
            ],
        ),
    ]
