# Generated by Django 3.1.8 on 2021-05-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210523_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvideo',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='event.event'),
        ),
    ]
