# Generated by Django 3.1.3 on 2020-11-23 17:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVideoUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(unique=True, validators=[django.core.validators.RegexValidator(message='URL must be sourced from youtube.', regex='https:\\/\\/www\\.youtube\\.com\\/*')]), size=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RootEvent', to='event.event')),
            ],
        ),
    ]
