# Generated by Django 3.1.3 on 2020-11-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventvideourls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventvideourls',
            old_name='video_url',
            new_name='video_urls',
        ),
    ]
