# Generated by Django 3.1.8 on 2021-05-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventcomment_eventinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventphoto',
            options={'verbose_name': 'Event Image', 'verbose_name_plural': 'Event Image'},
        ),
        migrations.AlterModelOptions(
            name='eventvideo',
            options={'verbose_name': 'Event Video', 'verbose_name_plural': 'Event Videos'},
        ),
        migrations.AlterModelOptions(
            name='eventvideourl',
            options={'verbose_name': 'Event Video URL', 'verbose_name_plural': 'Event URLs'},
        ),
    ]
