# Generated by Django 3.1.1 on 2020-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adfile',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
