# Generated by Django 3.1.1 on 2020-09-16 10:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ad_file', '0002_adfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adfile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=20, region=None, unique=True),
            preserve_default=False,
        ),
    ]
