COUNTRY_CHOICES = (
    ("AFG", "Afghanistan"),
    ("IND", "India"),
    ("PAK", "Pakistan"),
    ("BAN", "Bangladesh"),
    ("SRI", "Sri Lanka"),
    ("NEP", "Nepal"),
    ("BHU", "Bhutan"),
    ("MAL", "Maldives")
)

DISTRICT_CHOICES = (
    ("BHOJPUR", "Bhojpur"),
    ("DHANKUTA", "Dhankuta"),
    ("ILAM", "Ilam"),
    ("JHAPA", "Jhapa"),
    ("KHOTANG", "Khotang"),
    ("MORANG", "Morang"),
    ("OKHALDHUNGA", "Okhaldhunga"),
    ("PANCHTHAR", "Panchthar"),
    ("SANKHUWASABHA", "Sankhuwasabha"),
    ("SOLUKHUMBU", "Solukhumbu"),
    ("SUNSARI", "Sunsari"),
    ("TAPLEJUNG", "Taplejung"),
    ("TERATHUM", "Terhathum"),
    ("UDAYAPUR", "Udayapur"),

    ("BARA", "Bara"),
    ("PARSA", "Parsa"),
    ("DHANUSHA", "Dhanusha"),
    ("MAHOTTARI", "Mahottari"),
    ("RAUTAHAT", "Rautahat"),
    ("SAPTARI", "Saptari"),
    ("SARLAHI", "Sarlahi"),
    ("SIRAHA", "Siraha"),

    ("BHAKTAPUR", "Bhaktapur"),
    ("CHITWAN", "Chitwan"),
    ("DHADING", "Dhading"),
    ("DOLAKHA", "Dolakha"),
    ("KATHMANDU", "Kathmandu"),
    ("KAVREPALANCHOK", "Kavrepalanchok"),
    ("LALITPUR", "Lalitpur"),
    ("MAKWANPUR", "Makwanpur"),
    ("NUWAKOT", "Nuwakot"),
    ("RAMECHHAP", "Ramechhap"),
    ("RASUWA", "Rasuwa"),
    ("SINDHULI", "Sindhuli"),
    ("SINDHUPALCHOK", "Sindhupalchok"),

    ("BAGLUNG", "Baglung"),
    ("GORKHA", "Gorkha"),
    ("KASKI", "Kaski"),
    ("LAMJUNG", "Lamjung"),
    ("MANANG", "Manang"),
    ("MUSTANG", "Mustang"),
    ("MYAGDI", "Myagdi"),
    ("NAWALPUR", "Nawalpur"),
    ("PARBAT", "Parbat"),
    ("SYANGJA", "Syangja"),
    ("TANAHUN", "Tanahun"),

    ("ARGHAKHACHI", "Arghakhanchi"),
    ("BANKE", "Banke"),
    ("BARDIYA", "Bardiya"),
    ("DANG", "Dang"),
    ("RUKUM", "Rukum"),
    ("GULMI", "Gulmi"),
    ("KAPILAVASTU", "Kapilavastu"),
    ("PARASI", "Parasi"),
    ("PALPA", "Palpa"),
    ("PYUTHAN", "Pyuthan"),
    ("ROLPA", "Rolpa"),
    ("RUPANDEHI", "Rupandehi"),

    ("DAILEKH", "Dailekh"),
    ("DOLPA", "Dolpa"),
    ("HUMLA", "Humla"),
    ("JAJARKOT", "Jajarkot"),
    ("JUMLA", "Jumla"),
    ("KALIKOT", "Kalikot"),
    ("MUGU", "Mugu"),
    ("SALYAN", "Salyan"),
    ("SURKHET", "Surkhet"),
    ("RUKUM", "Rukum"),

    ("ACHHAM", "Achham"),
    ("BAITADI", "Baitadi"),
    ("BAJHANG", "Bajhang"),
    ("BAJURA", "Bajura"),
    ("DADELDHURA", "Dadeldhura"),
    ("DARCHULA", "Darchula"),
    ("DOTI", "Doti"),
    ("KAILALI", "Kailali"),
    ("KANCHANPUR", "Kanchanpur")
)
