MEMBER_ROLE_CHOICES = (
    ("Branch Chief", "Branch Chief"),
    ("Branch Vice Chief", "Branch Vice Chief"),
    ("Leader", "Leader"),
    ("Double Star Leader", "Double Star Leader"),
    ("Single Star Leader", "Single Star Leader"),
    ("MAINTAINER", "MAINTAINER")
)

COUNTRIES = (
    ("AFG", "Afghanistan"),
    ("IND", "India"),
    ("PAK", "Pakistan"),
    ("BAN", "Bangladesh"),
    ("SRI", "Sri Lanka"),
    ("NEP", "Nepal"),
    ("BHU", "Bhutan"),
    ("MAL", "Maldives")
)

PROVINCES = (
    ("Nepal", "Province No. 1", 1),
    ("Nepal", "Province No. 2", 2),
    ("Nepal", "Bagmati Pradesh", 3),
    ("Nepal", "Gandaki Pradesh", 4),
    ("Nepal", "Province No. 5", 5),
    ("Nepal", "Karnali Pradesh", 6),
    ("Nepal", "Sudurpashchim Pradesh", 7),
)

PERMISSIONS = [
    'add_member', 'approve_member', 'change_member', 'delete_member', 'view_member',
    'add_memberbranch', 'change_memberbranch', 'delete_memberbranch', 'view_memberbranch',
    'add_memberrole', 'change_memberrole', 'delete_memberrole', 'view_memberrole',
    'add_profile', 'change_profile', 'delete_profile', 'view_profile',
    'add_profileimage', 'change_profileimage', 'delete_profileimage', 'view_profileimage',
    'add_resetpasswordcode', 'change_resetpasswordcode', 'delete_resetpasswordcode', 'view_resetpasswordcode',
    'add_logentry', 'change_logentry', 'delete_logentry', 'view_logentry',
    'add_advertisement', 'change_advertisement', 'delete_advertisement', 'view_advertisement',
    'add_group', 'change_group', 'delete_group', 'view_group',
    'add_permission', 'change_permission', 'delete_permission', 'view_permission',
    'add_user', 'change_user', 'delete_user', 'view_user',
    'add_token', 'change_token', 'delete_token', 'view_token',
    'add_tokenproxy', 'change_tokenproxy', 'delete_tokenproxy', 'view_tokenproxy',
    'add_branch', 'approve_branch', 'change_branch', 'delete_branch', 'view_branch',
    'add_contenttype', 'change_contenttype', 'delete_contenttype', 'view_contenttype',
    'add_event', 'approve_event', 'change_event', 'delete_event', 'view_event',
    'add_eventphoto', 'change_eventphoto', 'delete_eventphoto', 'view_eventphoto',
    'add_eventvideourls', 'change_eventvideourls', 'delete_eventvideourls', 'view_eventvideourls',
    'add_country', 'change_country', 'delete_country', 'view_country',
    'add_district', 'change_district', 'delete_district', 'view_district',
    'add_municipality', 'change_municipality', 'delete_municipality', 'view_municipality',
    'add_municipalityward', 'change_municipalityward', 'delete_municipalityward', 'view_municipalityward',
    'add_province', 'change_province', 'delete_province', 'view_province',
    'add_vdc', 'change_vdc', 'delete_vdc', 'view_vdc',
    'add_vdcward', 'change_vdcward', 'delete_vdcward', 'view_vdcward',
    'add_article', 'change_article', 'delete_article', 'view_article',
    'add_articleimage', 'change_articleimage', 'delete_articleimage', 'view_articleimage',
    'add_bookmarkmedia', 'change_bookmarkmedia', 'delete_bookmarkmedia', 'view_bookmarkmedia',
    'add_comment', 'change_comment', 'delete_comment', 'view_comment',
    'add_love', 'change_love', 'delete_love', 'view_love',
    'add_media', 'approve_media', 'change_media', 'delete_media', 'view_media',
    'add_multimedia', 'change_multimedia', 'delete_multimedia', 'view_multimedia',
    'add_multimediaaudio', 'change_multimediaaudio', 'delete_multimediaaudio', 'view_multimediaaudio',
    'add_multimediaimage', 'change_multimediaimage', 'delete_multimediaimage', 'view_multimediaimage',
    'add_multimediavideo', 'change_multimediavideo', 'delete_multimediavideo', 'view_multimediavideo',
    'add_pinmedia', 'change_pinmedia', 'delete_pinmedia', 'view_pinmedia',
    'add_session', 'change_session', 'delete_session', 'view_session'
]

DISTRICTS = (
    (1, "Bhojpur"),
    (1, "Dhankuta"),
    (1, "Ilam"),
    (1, "Jhapa"),
    (1, "Khotang"),
    (1, "Morang"),
    (1, "Okhaldhunga"),
    (1, "Panchthar"),
    (1, "Sankhuwasabha"),
    (1, "Solukhumbu"),
    (1, "Sunsari"),
    (1, "Taplejung"),
    (1, "Terhathum"),
    (1, "Udayapur"),

    (2, "Bara"),
    (2, "Parsa"),
    (2, "Dhanusha"),
    (2, "Mahottari"),
    (2, "Rautahat"),
    (2, "Saptari"),
    (2, "Sarlahi"),
    (2, "Siraha"),

    (3, "Bhaktapur"),
    (3, "Chitwan"),
    (3, "Dhading"),
    (3, "Dolakha"),
    (3, "Kathmandu"),
    (3, "Kavrepalanchok"),
    (3, "Lalitpur"),
    (3, "Makwanpur"),
    (3, "Nuwakot"),
    (3, "Ramechhap"),
    (3, "Rasuwa"),
    (3, "Sindhuli"),
    (3, "Sindhupalchok"),

    (4, "Baglung"),
    (4, "Gorkha"),
    (4, "Kaski"),
    (4, "Lamjung"),
    (4, "Manang"),
    (4, "Mustang"),
    (4, "Myagdi"),
    (4, "Nawalpur"),
    (4, "Parbat"),
    (4, "Syangja"),
    (4, "Tanahun"),

    (5, "Arghakhanchi"),
    (5, "Banke"),
    (5, "Bardiya"),
    (5, "Dang"),
    (5, "Eastern Rukum"),
    (5, "Gulmi"),
    (5, "Kapilavastu"),
    (5, "Parasi"),
    (5, "Palpa"),
    (5, "Pyuthan"),
    (5, "Rolpa"),
    (5, "Rupandehi"),

    (6, "Dailekh"),
    (6, "Dolpa"),
    (6, "Humla"),
    (6, "Jajarkot"),
    (6, "Jumla"),
    (6, "Kalikot"),
    (6, "Mugu"),
    (6, "Salyan"),
    (6, "Surkhet"),
    (6, "Western Rukum"),

    (7, "Achham"),
    (7, "Baitadi"),
    (7, "Bajhang"),
    (7, "Bajura"),
    (7, "Dadeldhura"),
    (7, "Darchula"),
    (7, "Doti"),
    (7, "Kailali"),
    (7, "Kanchanpur")
)
