MUNICIPALITIES = (
    ("Sidingba Rural Municipality", "Taplejung"),
    ("Meringden Rural Municipality", "Taplejung"),
    ("Maiwakhola Rural Municipality", "Taplejung"),
    ("Phaktanglung Rural Municipality", "Taplejung"),
    ("Sirijangha Rural Municipality", "Taplejung"),
    ("Mikwakhola Rural Municipality", "Taplejung"),
    ("Aathrai Tribeni Rural Municipality", "Taplejung"),
    ("Pathivara Yangwarak Rural Municipality", "Taplejung"),
    ("Phungling Municipality", "Taplejung"),
    ("Makalu Rural Municipality", "Sankhuwasabha"),
    ("Chichila Rural Municipality", "Sankhuwasabha"),
    ("Silichong Rural Municipality", "Sankhuwasabha"),
    ("Bhotkhola Rural Municipality", "Sankhuwasabha"),
    ("Sabhapokhari Rural Municipality", "Sankhuwasabha"),
    ("Dharmadevi Municipality", "Sankhuwasabha"),
    ("Madi Municipality Sankhuwasabha", "Sankhuwasabha"),
    ("Panchakhapan Municipality", "Sankhuwasabha"),
    ("Chainpur Municipality", "Sankhuwasabha"),
    ("Khandbari Municipality", "Sankhuwasabha"),
    ("Sotang Rural Municipality", "Solukhumbu"),
    ("Mahakulung Rural Municipality", "Solukhumbu"),
    ("Likhupike Rural Municipality", "Solukhumbu"),
    ("Nechasalyan Rural Municipality", "Solukhumbu"),
    ("Thulung Dudhkoshi Rural Municipality", "Solukhumbu"),
    ("Maapya Dudhkoshi Rural Municipality", "Solukhumbu"),
    ("Khumbupasanglahmu Rural Municipality", "Solukhumbu"),
    ("Solududhakunda Municipality", "Solukhumbu"),
    ("Likhu Rural Municipality Okhaldhunga", "Okhaldhunga"),
    ("Molung Rural Municipality", "Okhaldhunga"),
    ("Sunkoshi Rural Municipality Okhaldhunga", "Okhaldhunga"),
    ("Champadevi Rural Municipality", "Okhaldhunga"),
    ("Chisankhugadhi Rural Municipality", "Okhaldhunga"),
    ("Khijidemba Rural Municipality", "Okhaldhunga"),
    ("Manebhanjyang Rural Municipality", "Okhaldhunga"),
    ("Siddhicharan Municipality", "Okhaldhunga"),
    ("Sakela Rural Municipality", "Khotang"),
    ("Khotehang Rural Municipality", "Khotang"),
    ("Barahapokhari Rural Municipality", "Khotang"),
    ("Ainselukhark Rural Municipality", "Khotang"),
    ("Rawa Besi Rural Municipality", "Khotang"),
    ("Kepilasagadhi Rural Municipality", "Khotang"),
    ("Jantedhunga Rural Municipality", "Khotang"),
    ("Diprung Chuichumma Rural Municipality", "Khotang"),
    ("Halesi Tuwachung Municipality", "Khotang"),
    ("Diktel Rupakot Majhuwagadhi Municipality", "Khotang"),
    ("Arun Rural Municipality", "Bhojpur"),
    ("Aamchowk Rural Municipality", "Bhojpur"),
    ("Hatuwagadhi Rural Municipality", "Bhojpur"),
    ("Pauwadungma Rural Municipality", "Bhojpur"),
    ("Temkemaiyung Rural Municipality", "Bhojpur"),
    ("Salpasilichho Rural Municipality", "Bhojpur"),
    ("Ramprasad Rai Rural Municipality", "Bhojpur"),
    ("Shadananda Municipality", "Bhojpur"),
    ("Bhojpur Municipality", "Bhojpur"),
    ("Chaubise Rural Municipality", "Dhankuta"),
    ("Shahidbhumi Rural Municipality", "Dhankuta"),
    ("Sangurigadhi Rural Municipality", "Dhankuta"),
    ("Chhathar Jorpati Rural Municipality", "Dhankuta"),
    ("Pakhribas Municipality", "Dhankuta"),
    ("Mahalaxmi Municipality Dhankuta", "Dhankuta"),
    ("Dhankuta Municipality", "Dhankuta"),
    ("Chhathar Rural Municipality", "Terhathum"),
    ("Phedap Rural Municipality", "Terhathum"),
    ("Aathrai Rural Municipality", "Terhathum"),
    ("Menchayam Rural Municipality", "Terhathum"),
    ("Laligurans Municipality", "Terhathum"),
    ("Myanglung Municipality", "Terhathum"),
    ("Yangwarak Rural Municipality", "PANCHTHAR"),
    ("Hilihang Rural Municipality", "PANCHTHAR"),
    ("Falelung Rural Municipality", "PANCHTHAR"),
    ("Tumbewa Rural Municipality", "PANCHTHAR"),
    ("Kummayak Rural Municipality", "PANCHTHAR"),
    ("Miklajung Rural Municipality", "PANCHTHAR"),
    ("Falgunanda Rural Municipality", "PANCHTHAR"),
    ("Phidim Municipality", "PANCHTHAR"),
    ("Rong Rural Municipality", "ILAM"),
    ("Mangsebung Rural Municipality", "ILAM"),
    ("Chulachuli Rural Municipality", "ILAM"),
    ("Sandakpur Rural Municipality", "ILAM"),
    ("Fakphokthum Rural Municipality", "ILAM"),
    ("Maijogmai Rural Municipality", "ILAM"),
    ("Illam Municipality", "ILAM"),
    ("Mai Municipality", "ILAM"),
    ("Deumai Municipality", "ILAM"),
    ("Suryodaya Municipality", "ILAM"),
    ("Kamal Rural Municipality", "JHAPA"),
    ("Jhapa Rural Municipality", "JHAPA"),
    ("Kachankawal Rural Municipality", "JHAPA"),
    ("Gauriganj Rural Municipality", "JHAPA"),
    ("Barhadashi Rural Municipality", "JHAPA"),
    ("Haldibari Rural Municipality", "JHAPA"),
    ("Buddhashanti Rural Municipality", "JHAPA"),
    ("Shivasataxi Municipality", "JHAPA"),
    ("Bhadrapur Municipality", "JHAPA"),
    ("Kankai Municipality", "JHAPA"),
    ("Birtamod Municipality", "JHAPA"),
    ("Mechinagar Municipality", "JHAPA"),
    ("Damak Municipality", "JHAPA"),
    ("Arjundhara Municipality", "JHAPA"),
    ("Gauradhaha Municipality", "JHAPA"),
    ("Jahada Rural Municipality", "MORANG"),
    ("Katahari Rural Municipality", "MORANG"),
    ("Gramthan Rural Municipality", "MORANG"),
    ("Dhanpalthan Rural Municipality", "MORANG"),
    ("Kerabari Rural Municipality", "MORANG"),
    ("Budhiganga Rural Municipality", "MORANG"),
    ("Kanepokhari Rural Municipality", "MORANG"),
    ("Mikla-jung Rural Municipality", "MORANG"),
    ("Letang Municipality", "MORANG"),
    ("Sunwarshi Municipality", "MORANG"),
    ("Rangeli Municipality", "MORANG"),
    ("Patahrishanishchare Municipality", "MORANG"),
    ("Biratnagar Metropolitian City", "MORANG"),
    ("Uralabari Municipality", "MORANG"),
    ("Belbari Municipality", "MORANG"),
    ("Sundarharaicha Municipality", "MORANG"),
    ("Ratuwamai Municipality", "MORANG"),
    ("Gadhi Rural Municipality", "SUNSARI"),
    ("Koshi Rural Municipality", "SUNSARI"),
    ("Barju Rural Municipality", "SUNSARI"),
    ("Harinagar Rural Municipality", "SUNSARI"),
    ("Dewanganj Rural Municipality", "SUNSARI"),
    ("Bhokraha Narsing Rural Municipality", "SUNSARI"),
    ("Ramdhuni Municipality", "SUNSARI"),
    ("Barahchhetra Municipality", "SUNSARI"),
    ("Duhabi Municipality", "SUNSARI"),
    ("Inaruwa Municipality", "SUNSARI"),
    ("Tapli Rural Municipality", "UDAYAPUR"),
    ("Rautamai Rural Municipality", "UDAYAPUR"),
    ("Udayapurgadhi Rural Municipality", "UDAYAPUR"),
    ("Limchungbung Rural Municipality", "UDAYAPUR"),
    ("Chaudandigadhi Municipality", "UDAYAPUR"),
    ("Triyuga Municipality", "UDAYAPUR"),
    ("Katari Municipality", "UDAYAPUR"),
    ("Belaka Municipality", "UDAYAPUR"),
    ("Rajgadh Rural Municipality", "SAPTARI"),
    ("Rupani Rural Municipality", "SAPTARI"),
    ("Tirahut Rural Municipality", "SAPTARI"),
    ("Mahadeva Rural Municipality", "SAPTARI"),
    ("Bishnupur Rural Municipality Saptari", "SAPTARI"),
    ("Chhinnamasta Rural Municipality", "SAPTARI"),
    ("Balan Bihul Rural Municipality", "SAPTARI"),
    ("Tilathi Koiladi Rural Municipality", "SAPTARI"),
    ("Agnisair Krishna Savaran Rural Municipality", "SAPTARI"),
    ("Hanumannagar Kankalini Municipality", "SAPTARI"),
    ("Kanchanrup Municipality", "SAPTARI"),
    ("Rajbiraj Municipality", "SAPTARI"),
    ("Khadak Municipality", "SAPTARI"),
    ("Dakneshwori Municipality", "SAPTARI"),
    ("Saptakoshi Rural Municipality", "SAPTARI"),
    ("Surunga Municipality", "SAPTARI"),
    ("Shambhunath Municipality", "SAPTARI"),
    ("Bode Barsain Municipality", "SAPTARI"),
    ("Aurahi Rural Municipality", "SIRAHA"),
    ("Naraha Rural Municipality", "SIRAHA"),
    ("Arnama Rural Municipality", "SIRAHA"),
    ("Bhagawanpur Rural Municipality", "SIRAHA"),
    ("Nawarajpur Rural Municipality", "SIRAHA"),
    ("Bishnupur Rural Municipality", "SIRAHA"),
    ("Bariyarpatti Rural Municipality", "SIRAHA"),
    ("Laxmipur Patari Rural Municipality", "SIRAHA"),
    ("Sakhuwanankarkatti Rural Municipality", "SIRAHA"),
    ("Mirchaiya Municipality", "SIRAHA"),
    ("Lahan Municipality", "SIRAHA"),
    ("Siraha Municipality", "SIRAHA"),
    ("Dhangadhimai Municipality", "SIRAHA"),
    ("Kalyanpur Municipality", "SIRAHA"),
    ("Karjanha Municipality", "SIRAHA"),
    ("Golbazar Municipality", "SIRAHA"),
    ("Sukhipur Municipality", "SIRAHA"),
    ("Aaurahi Rural Municipality", "Dhanusha"),
    ("Dhanauji Rural Municipality", "Dhanusha"),
    ("Bateshwor Rural Municipality", "Dhanusha"),
    ("Janaknandani Rural Municipality", "Dhanusha"),
    ("Lakshminiya Rural Municipality", "Dhanusha"),
    ("Mukhiyapatti Musarmiya Rural Municipality", "Dhanusha"),
    ("Mithila Bihari Municipality", "Dhanusha"),
    ("Kamala Municipality", "Dhanusha"),
    ("Nagarain Municipality", "Dhanusha"),
    ("Ganeshman Charnath Municipality", "Dhanusha"),
    ("Mithila Municipality", "Dhanusha"),
    ("Dhanushadham Municipality", "Dhanusha"),
    ("Bideha Municipality", "Dhanusha"),
    ("Sabaila Municipality", "Dhanusha"),
    ("Hansapur Municipality", "Dhanusha"),
    ("Sahidnagar Municipality", "Dhanusha"),
    ("Chhireshwornath Municipality", "Dhanusha"),
    ("Pipra Rural Municipality", "MAHOTTARI"),
    ("Sonama Rural Municipality", "MAHOTTARI"),
    ("Samsi Rural Municipality", "MAHOTTARI"),
    ("Ekdanra Rural Municipality", "MAHOTTARI"),
    ("Mahottari Rural Municipality", "MAHOTTARI"),
    ("Gaushala Municipality", "MAHOTTARI"),
    ("Ramgopalpur Municipality", "MAHOTTARI"),
    ("Aurahi Municipality", "MAHOTTARI"),
    ("Bardibas Municipality", "MAHOTTARI"),
    ("Bhangaha Municipality", "MAHOTTARI"),
    ("Jaleswor Municipality", "MAHOTTARI"),
    ("Balwa Municipality", "MAHOTTARI"),
    ("Manra Siswa Municipality", "MAHOTTARI"),
    ("Matihani Municipality", "MAHOTTARI"),
    ("Loharpatti Municipality", "MAHOTTARI"),
    ("Dhankaul Rural Municipality", "SARLAHI"),
    ("Parsa Rural Municipality", "SARLAHI"),
    ("Bishnu Rural Municipality", "SARLAHI"),
    ("Ramnagar Rural Municipality", "SARLAHI"),
    ("Kaudena Rural Municipality", "SARLAHI"),
    ("Basbariya Rural Municipality", "SARLAHI"),
    ("Chandranagar Rural Municipality", "SARLAHI"),
    ("Chakraghatta Rural Municipality", "SARLAHI"),
    ("Bramhapuri Rural Municipality", "SARLAHI"),
    ("Barahathawa Municipality", "SARLAHI"),
    ("Haripur Municipality", "SARLAHI"),
    ("Ishworpur Municipality", "SARLAHI"),
    ("Lalbandi Municipality", "SARLAHI"),
    ("Malangawa Municipality", "SARLAHI"),
    ("Kabilasi Municipality", "SARLAHI"),
    ("Bagmati Municipality", "SARLAHI"),
    ("Hariwan Municipality", "SARLAHI"),
    ("Balara Municipality", "SARLAHI"),
    ("Haripurwa Municipality", "SARLAHI"),
    ("Godaita Municipality", "SARLAHI"),
    ("Yemunamai Rural Municipality", "RAUTAHAT"),
    ("Durga Bhagwati Rural Municipality", "RAUTAHAT"),
    ("Katahariya Municipality", "RAUTAHAT"),
    ("Maulapur Municipality", "RAUTAHAT"),
    ("Madhav Narayan Municipality", "RAUTAHAT"),
    ("Gaur Municipality", "RAUTAHAT"),
    ("Gujara Municipality", "RAUTAHAT"),
    ("Garuda Municipality", "RAUTAHAT"),
    ("Ishanath Municipality", "RAUTAHAT"),
    ("Chandrapur Municipality", "RAUTAHAT"),
    ("Dewahhi Gonahi Municipality", "RAUTAHAT"),
    ("Brindaban Municipality", "RAUTAHAT"),
    ("Rajpur Municipality", "RAUTAHAT"),
    ("Rajdevi Municipality", "RAUTAHAT"),
    ("Gadhimai Municipality", "RAUTAHAT"),
    ("Phatuwa Bijayapur Municipality", "RAUTAHAT"),
    ("Baudhimai Municipality", "RAUTAHAT"),
    ("Paroha Municipality", "RAUTAHAT"),
    ("Pheta Rural Municipality", "BARA"),
    ("Devtal Rural Municipality", "BARA"),
    ("Prasauni Rural Municipality", "BARA"),
    ("Suwarna Rural Municipality", "BARA"),
    ("Baragadhi Rural Municipality", "BARA"),
    ("Karaiyamai Rural Municipality", "BARA"),
    ("Parwanipur Rural Municipality", "BARA"),
    ("Bishrampur Rural Municipality", "BARA"),
    ("Adarshkotwal Rural Municipality", "BARA"),
    ("Pacharauta Municipality", "BARA"),
    ("Nijgadh Municipality", "BARA"),
    ("Simraungadh Municipality", "BARA"),
    ("Mahagadhimai Municipality", "BARA"),
    ("Kolhabi Municipality", "BARA"),
    ("Thori Rural Municipality", "PARSA"),
    ("Dhobini Rural Municipality", "PARSA"),
    ("Chhipaharmai Rural Municipality", "PARSA"),
    ("Jirabhawani Rural Municipality", "PARSA"),
    ("Jagarnathpur Rural Municipality", "PARSA"),
    ("Kalikamai Rural Municipality", "PARSA"),
    ("Bindabasini Rural Municipality", "PARSA"),
    ("Pakahamainpur Rural Municipality", "PARSA"),
    ("SakhuwaPrasauni Rural Municipality", "PARSA"),
    ("Paterwasugauli Rural Municipality", "PARSA"),
    ("Birgunj Metropolitian City", "PARSA"),
    ("Bahudaramai Municipality", "PARSA"),
    ("Pokhariya Municipality", "PARSA"),
    ("Parsagadhi Municipality", "PARSA"),
    ("Bigu Rural Municipality", "DOLAKHA"),
    ("Sailung Rural Municipality", "DOLAKHA"),
    ("Melung Rural Municipality", "DOLAKHA"),
    ("Baiteshwor Rural Municipality", "DOLAKHA"),
    ("Tamakoshi Rural Municipality", "DOLAKHA"),
    ("Gaurishankar Rural Municipality", "DOLAKHA"),
    ("Kalinchok Rural Municipality", "DOLAKHA"),
    ("Jiri Municipality", "DOLAKHA"),
    ("Bhimeshwor Municipality", "DOLAKHA"),
    ("Jugal Rural Municipality", "SINDHUPALCHOK"),
    ("Balefi Rural Municipality", "SINDHUPALCHOK"),
    ("Sunkoshi Rural Municipality Sindhupalchok", "SINDHUPALCHOK"),
    ("Helambu Rural Municipality", "SINDHUPALCHOK"),
    ("Bhotekoshi Rural Municipality", "SINDHUPALCHOK"),
    ("Lisangkhu Pakhar Rural Municipality", "SINDHUPALCHOK"),
    ("Indrawati Rural Municipality", "SINDHUPALCHOK"),
    ("Tripurasundari Rural Municipality", "SINDHUPALCHOK"),
    ("Panchpokhari Thangpal Rural Municipality", "SINDHUPALCHOK"),
    ("Chautara SangachokGadhi Municipality", "SINDHUPALCHOK"),
    ("Barhabise Municipality", "SINDHUPALCHOK"),
    ("Melamchi Municipality", "SINDHUPALCHOK"),
    ("Kalika Rural Municipality Rasuwa", "RASUWA"),
    ("Naukunda Rural Municipality", "RASUWA"),
    ("Uttargaya Rural Municipality", "RASUWA"),
    ("Gosaikunda Rural Municipality", "RASUWA"),
    ("Amachodingmo Rural Municipality", "RASUWA"),
    ("Gajuri Rural Municipality", "DHADING"),
    ("Galchi Rural Municipality", "DHADING"),
    ("Thakre Rural Municipality", "DHADING"),
    ("Siddhalek Rural Municipality", "DHADING"),
    ("Khaniyabash Rural Municipality", "DHADING"),
    ("Jwalamukhi Rural Municipality", "DHADING"),
    ("Gangajamuna Rural Municipality", "DHADING"),
    ("Rubi Valley Rural Municipality", "DHADING"),
    ("Tripura Sundari Rural Municipality", "DHADING"),
    ("Netrawati Dabjong Rural Municipality", "DHADING"),
    ("Benighat Rorang Rural Municipality", "DHADING"),
    ("Nilakantha Municipality", "DHADING"),
    ("Dhunibesi Municipality", "DHADING"),
    ("Kakani Rural Municipality", "NUWAKOT"),
    ("Tadi Rural Municipality", "NUWAKOT"),
    ("Likhu Rural Municipality Nuwakot", "NUWAKOT"),
    ("Myagang Rural Municipality", "NUWAKOT"),
    ("Shivapuri Rural Municipality", "NUWAKOT"),
    ("Kispang Rural Municipality", "NUWAKOT"),
    ("Suryagadhi Rural Municipality", "NUWAKOT"),
    ("Tarkeshwar Rural Municipality", "NUWAKOT"),
    ("Panchakanya Rural Municipality", "NUWAKOT"),
    ("Dupcheshwar Rural Municipality", "NUWAKOT"),
    ("Belkotgadhi Municipality", "NUWAKOT"),
    ("Bidur Municipality", "NUWAKOT"),
    ("Kirtipur Municipality", "KATHMANDU"),
    ("Shankharapur Municipality", "KATHMANDU"),
    ("Nagarjun Municipality", "KATHMANDU"),
    ("Kageshwori Manahora Municipality", "KATHMANDU"),
    ("Dakshinkali Municipality", "KATHMANDU"),
    ("Budhanilakantha Municipality", "KATHMANDU"),
    ("Tarakeshwor Municipality", "KATHMANDU"),
    ("Kathmandu Metropolitian City", "KATHMANDU"),
    ("Tokha Municipality", "KATHMANDU"),
    ("Chandragiri Municipality", "KATHMANDU"),
    ("Gokarneshwor Municipality", "KATHMANDU"),
    ("Changunarayan Municipality", "BHAKTAPUR"),
    ("Suryabinayak Municipality", "BHAKTAPUR"),
    ("Bhaktapur Municipality", "BHAKTAPUR"),
    ("Madhyapur Thimi Municipality", "BHAKTAPUR"),
    ("Bagmati Rural Municipality Lalitpur", "LALITPUR"),
    ("Mahankal Rural Municipality", "LALITPUR"),
    ("Konjyosom Rural Municipality", "LALITPUR"),
    ("Lalitpur Metropolitian City", "LALITPUR"),
    ("Mahalaxmi Municipality", "LALITPUR"),
    ("Godawari Municipality Lalitpur", "LALITPUR"),
    ("Roshi Rural Municipality", "KAVREPALANCHOK"),
    ("Temal Rural Municipality", "KAVREPALANCHOK"),
    ("Bhumlu Rural Municipality", "KAVREPALANCHOK"),
    ("Mahabharat Rural Municipality", "KAVREPALANCHOK"),
    ("Bethanchowk Rural Municipality", "KAVREPALANCHOK"),
    ("Khanikhola Rural Municipality", "KAVREPALANCHOK"),
    ("Chaurideurali Rural Municipality", "KAVREPALANCHOK"),
    ("Banepa Municipality", "KAVREPALANCHOK"),
    ("Mandandeupur Municipality", "KAVREPALANCHOK"),
    ("Dhulikhel Municipality", "KAVREPALANCHOK"),
    ("Panauti Municipality", "KAVREPALANCHOK"),
    ("Namobuddha Municipality", "KAVREPALANCHOK"),
    ("Panchkhal Municipality", "KAVREPALANCHOK"),
    ("Sunapati Rural Municipality", "RAMECHHAP"),
    ("Doramba Rural Municipality", "RAMECHHAP"),
    ("Umakunda Rural Municipality", "RAMECHHAP"),
    ("Khadadevi Rural Municipality", "RAMECHHAP"),
    ("Gokulganga Rural Municipality", "RAMECHHAP"),
    ("Likhu Tamakoshi Rural Municipality", "RAMECHHAP"),
    ("Manthali Municipality", "RAMECHHAP"),
    ("Ramechhap Municipality", "RAMECHHAP"),
    ("Marin Rural Municipality", "SINDHULI"),
    ("Phikkal Rural Municipality", "SINDHULI"),
    ("Tinpatan Rural Municipality", "SINDHULI"),
    ("Sunkoshi Rural Municipality Sindhuli", "SINDHULI"),
    ("Golanjor Rural Municipality", "SINDHULI"),
    ("Ghanglekh Rural Municipality", "SINDHULI"),
    ("Hariharpurgadhi Rural Municipality", "SINDHULI"),
    ("Dudhouli Municipality", "SINDHULI"),
    ("Kamalamai Municipality", "SINDHULI"),
    ("Bakaiya Rural Municipality", "MAKWANPUR"),
    ("Kailash Rural Municipality", "MAKWANPUR"),
    ("Manahari Rural Municipality", "MAKWANPUR"),
    ("Bhimphedi Rural Municipality", "MAKWANPUR"),
    ("Bagmati Rural Municipality Makwanpur", "MAKWANPUR"),
    ("Raksirang Rural Municipality", "MAKWANPUR"),
    ("Makawanpurgadhi Rural Municipality", "MAKWANPUR"),
    ("Indrasarowar Rural Municipality", "MAKWANPUR"),
    ("Thaha Municipality", "MAKWANPUR"),
    ("Ichchhyakamana Rural Municipality", "Chitwan"),
    ("Bharatpur Metropolitian City", "Chitwan"),
    ("Kalika Municipality", "Chitwan"),
    ("Khairahani Municipality", "Chitwan"),
    ("Madi Municipality Chitwan", "Chitwan"),
    ("Rapti Municipality", "Chitwan"),
    ("Ratnanagar Municipality", "Chitwan"),
    ("Gandaki Rural Municipality", "GORKHA"),
    ("Dharche Rural Municipality", "GORKHA"),
    ("Aarughat Rural Municipality", "GORKHA"),
    ("Ajirkot Rural Municipality", "GORKHA"),
    ("Sahid Lakhan Rural Municipality", "GORKHA"),
    ("Siranchok Rural Municipality", "GORKHA"),
    ("Bhimsenthapa Rural Municipality", "GORKHA"),
    ("Chum Nubri Rural Municipality", "GORKHA"),
    ("Barpak Sulikot Rural Municipality", "GORKHA"),
    ("Palungtar Municipality", "GORKHA"),
    ("Gorkha Municipality", "GORKHA"),
    ("Chame Rural Municipality", "MANANG"),
    ("Narshon Rural Municipality", "MANANG"),
    ("Narpa Bhumi Rural Municipality", "MANANG"),
    ("Manang Ingshyang Rural Municipality", "MANANG"),
    ("Thasang Rural Municipality", "MUSTANG"),
    ("Gharapjhong Rural Municipality", "MUSTANG"),
    ("Lomanthang Rural Municipality", "MUSTANG"),
    ("Waragung Muktikhsetra Rural Municipality", "MUSTANG"),
    ("Mangala Rural Municipality", "MYAGDI"),
    ("Malika Rural Municipality Myagdi", "MYAGDI"),
    ("Raghuganga Rural Municipality", "MYAGDI"),
    ("Dhaulagiri Rural Municipality", "MYAGDI"),
    ("Annapurna Rural Municipality Myagdi", "MYAGDI"),
    ("Beni Municipality", "MYAGDI"),
    ("Rupa Rural Municipality", "KASKI"),
    ("Madi Rural Municipality Kaski", "KASKI"),
    ("Annapurna Rural Municipality Kaski", "KASKI"),
    ("Machhapuchchhre Rural Municipality", "KASKI"),
    ("Pokhara Metropolitian City", "KASKI"),
    ("Dordi Rural Municipality", "LAMJUNG"),
    ("Dudhpokhari Rural Municipality", "LAMJUNG"),
    ("Marsyangdi Rural Municipality", "LAMJUNG"),
    ("Kwholasothar Rural Municipality", "LAMJUNG"),
    ("Sundarbazar Municipality", "LAMJUNG"),
    ("Besishahar Municipality", "LAMJUNG"),
    ("Rainas Municipality", "LAMJUNG"),
    ("MadhyaNepal Municipality", "LAMJUNG"),
    ("Ghiring Rural Municipality", "Tanahun"),
    ("Devghat Rural Municipality", "Tanahun"),
    ("Rhishing Rural Municipality", "Tanahun"),
    ("Myagde Rural Municipality", "Tanahun"),
    ("Bandipur Rural Municipality", "Tanahun"),
    ("Anbukhaireni Rural Municipality", "Tanahun"),
    ("Byas Municipality", "Tanahun"),
    ("Shuklagandaki Municipality", "Tanahun"),
    ("Bhimad Municipality", "Tanahun"),
    ("Bhanu Municipality", "Tanahun"),
    ("Harinas Rural Municipality", "SYANGJA"),
    ("Biruwa Rural Municipality", "SYANGJA"),
    ("Aandhikhola Rural Municipality", "SYANGJA"),
    ("Phedikhola Rural Municipality", "SYANGJA"),
    ("Kaligandagi Rural Municipality", "SYANGJA"),
    ("Arjunchaupari Rural Municipality", "SYANGJA"),
    ("Putalibazar Municipality", "SYANGJA"),
    ("Bhirkot Municipality", "SYANGJA"),
    ("Galyang Municipality", "SYANGJA"),
    ("Chapakot Municipality", "SYANGJA"),
    ("Waling Municipality", "SYANGJA"),
    ("Modi Rural Municipality", "PARBAT"),
    ("Painyu Rural Municipality", "PARBAT"),
    ("Jaljala Rural Municipality", "PARBAT"),
    ("Bihadi Rural Municipality", "PARBAT"),
    ("Mahashila Rural Municipality", "PARBAT"),
    ("Kushma Municipality", "PARBAT"),
    ("Phalebas Municipality", "PARBAT"),
    ("Bareng Rural Municipality", "BAGLUNG"),
    ("Badigad Rural Municipality", "BAGLUNG"),
    ("Nisikhola Rural Municipality", "BAGLUNG"),
    ("Kanthekhola Rural Municipality", "BAGLUNG"),
    ("Tara Khola Rural Municipality", "BAGLUNG"),
    ("Taman Khola Rural Municipality", "BAGLUNG"),
    ("Jaimuni Municipality", "BAGLUNG"),
    ("Baglung Municipality", "BAGLUNG"),
    ("Galkot Municipality", "BAGLUNG"),
    ("Dhorpatan Municipality", "BAGLUNG"),
    ("Madi Rural Municipality Rolpa", "ROLPA"),
    ("Thawang Rural Municipality", "ROLPA"),
    ("Sunchhahari Rural Municipality", "ROLPA"),
    ("Lungri Rural Municipality", "ROLPA"),
    ("Gangadev Rural Municipality", "ROLPA"),
    ("Tribeni Rural Municipality Rolpa", "ROLPA"),
    ("Pariwartan Rural Municipality", "ROLPA"),
    ("Runtigadi Rural Municipality", "ROLPA"),
    ("Sunil Smriti Rural Municipality", "ROLPA"),
    ("Rolpa Municipality", "ROLPA"),
    ("Ayirabati Rural Municipality", "PYUTHAN"),
    ("Gaumukhi Rural Municipality", "PYUTHAN"),
    ("Jhimruk Rural Municipality", "PYUTHAN"),
    ("Naubahini Rural Municipality", "PYUTHAN"),
    ("Mandavi Rural Municipality", "PYUTHAN"),
    ("Mallarani Rural Municipality", "PYUTHAN"),
    ("Sarumarani Rural Municipality", "PYUTHAN"),
    ("Pyuthan Municipality", "PYUTHAN"),
    ("Sworgadwary Municipality", "PYUTHAN"),
    ("Ruru Rural Municipality", "GULMI"),
    ("Isma Rural Municipality", "GULMI"),
    ("Madane Rural Municipality", "GULMI"),
    ("Malika Rural Municipality Gulmi", "GULMI"),
    ("Chatrakot Rural Municipality", "GULMI"),
    ("Dhurkot Rural Municipality", "GULMI"),
    ("Satyawati Rural Municipality", "GULMI"),
    ("Chandrakot Rural Municipality", "GULMI"),
    ("Kaligandaki Rural Municipality", "GULMI"),
    ("Gulmidarbar Rural Municipality", "GULMI"),
    ("Resunga Municipality", "GULMI"),
    ("Musikot Municipality", "GULMI"),
    ("Panini Rural Municipality", "ARGHAKHANCHI"),
    ("Chhatradev Rural Municipality", "ARGHAKHANCHI"),
    ("Malarani Rural Municipality", "ARGHAKHANCHI"),
    ("Bhumekasthan Municipality", "ARGHAKHANCHI"),
    ("Sitganga Municipality", "ARGHAKHANCHI"),
    ("Sandhikharka Municipality", "ARGHAKHANCHI"),
    ("Rambha Rural Municipality", "PALPA"),
    ("Tinau Rural Municipality", "PALPA"),
    ("Nisdi Rural Municipality", "PALPA"),
    ("Mathagadhi Rural Municipality", "PALPA"),
    ("Ribdikot Rural Municipality", "PALPA"),
    ("Purbakhola Rural Municipality", "PALPA"),
    ("Bagnaskali Rural Municipality", "PALPA"),
    ("Rainadevi Chhahara Rural Municipality", "PALPA"),
    ("Tansen Municipality", "PALPA"),
    ("Rampur Municipality", "PALPA"),
    ("Kanchan Rural Municipality", "RUPANDEHI"),
    ("Siyari Rural Municipality", "RUPANDEHI"),
    ("Rohini Rural Municipality", "RUPANDEHI"),
    ("Gaidahawa Rural Municipality", "RUPANDEHI"),
    ("Omsatiya Rural Municipality", "RUPANDEHI"),
    ("Sudhdhodhan Rural Municipality", "RUPANDEHI"),
    ("Mayadevi Rural Municipality Rupandehi", "RUPANDEHI"),
    ("Marchawari Rural Municipality", "RUPANDEHI"),
    ("Kotahimai Rural Municipality", "RUPANDEHI"),
    ("Sammarimai Rural Municipality", "RUPANDEHI"),
    ("Lumbini Sanskritik Municipality", "RUPANDEHI"),
    ("Devdaha Municipality", "RUPANDEHI"),
    ("Sainamaina Municipality", "RUPANDEHI"),
    ("Siddharthanagar Municipality", "RUPANDEHI"),
    ("Tillotama Municipality", "RUPANDEHI"),
    ("Yashodhara Rural Municipality", "Kapilavastu"),
    ("Bijayanagar Rural Municipality", "Kapilavastu"),
    ("Mayadevi Rural Municipality Kapilvastu", "Kapilavastu"),
    ("Suddhodhan Rural Municipality", "Kapilavastu"),
    ("Shivaraj Municipality", "Kapilavastu"),
    ("Kapilavastu Municipality", "Kapilavastu"),
    ("Buddhabhumi Municipality", "Kapilavastu"),
    ("Maharajgunj Municipality", "Kapilavastu"),
    ("Banganga Municipality", "Kapilavastu"),
    ("Krishnanagar Municipality", "Kapilavastu"),
    ("Babai Rural Municipality", "DANG"),
    ("Gadhawa Rural Municipality", "DANG"),
    ("Rapti Rural Municipality", "DANG"),
    ("Rajpur Rural Municipality", "DANG"),
    ("Dangisharan Rural Municipality", "DANG"),
    ("Shantinagar Rural Municipality", "DANG"),
    ("Banglachuli Rural Municipality", "DANG"),
    ("Lamahi Municipality", "DANG"),
    ("Khajura Rural Municipality", "BANKE"),
    ("Janki Rural Municipality", "BANKE"),
    ("Baijanath Rural Municipality", "BANKE"),
    ("Duduwa Rural Municipality", "BANKE"),
    ("Narainapur Rural Municipality", "BANKE"),
    ("Rapti Sonari Rural Municipality", "BANKE"),
    ("Kohalpur Municipality", "BANKE"),
    ("Geruwa Rural Municipality", "BARDIYA"),
    ("Badhaiyatal Rural Municipality", "BARDIYA"),
    ("Thakurbaba Municipality", "BARDIYA"),
    ("Bansagadhi Municipality", "BARDIYA"),
    ("Barbardiya Municipality", "BARDIYA"),
    ("Rajapur Municipality", "BARDIYA"),
    ("Madhuwan Municipality", "BARDIYA"),
    ("Gulariya Municipality", "BARDIYA"),
    ("Kaike Rural Municipality", "DOLPA"),
    ("Jagadulla Rural Municipality", "DOLPA"),
    ("Mudkechula Rural Municipality", "DOLPA"),
    ("Dolpo Buddha Rural Municipality", "DOLPA"),
    ("Shey Phoksundo Rural Municipality", "DOLPA"),
    ("Chharka Tangsong Rural Municipality", "DOLPA"),
    ("Tripurasundari Municipality", "DOLPA"),
    ("Thuli Bheri Municipality", "DOLPA"),
    ("Soru Rural Municipality", "MUGU"),
    ("Khatyad Rural Municipality", "MUGU"),
    ("Mugum Karmarong Rural Municipality", "MUGU"),
    ("Chhayanath Rara Municipality", "MUGU"),
    ("Simkot Rural Municipality", "HUMLA"),
    ("Namkha Rural Municipality", "HUMLA"),
    ("Chankheli Rural Municipality", "HUMLA"),
    ("Tanjakot Rural Municipality", "HUMLA"),
    ("Sarkegad Rural Municipality", "HUMLA"),
    ("Adanchuli Rural Municipality", "HUMLA"),
    ("Kharpunath Rural Municipality", "HUMLA"),
    ("Hima Rural Municipality", "JUMLA"),
    ("Tila Rural Municipality", "JUMLA"),
    ("Sinja Rural Municipality", "JUMLA"),
    ("Guthichaur Rural Municipality", "JUMLA"),
    ("Tatopani Rural Municipality", "JUMLA"),
    ("Patrasi Rural Municipality", "JUMLA"),
    ("Kanakasundari Rural Municipality", "JUMLA"),
    ("Chandannath Municipality", "JUMLA"),
    ("Mahawai Rural Municipality", "KALIKOT"),
    ("Palata Rural Municipality", "KALIKOT"),
    ("Naraharinath Rural Municipality", "KALIKOT"),
    ("Pachaljharana Rural Municipality", "KALIKOT"),
    ("Subha Kalika Rural Municipality", "KALIKOT"),
    ("Sanni Tribeni Rural Municipality", "KALIKOT"),
    ("Khandachakra Municipality", "KALIKOT"),
    ("Raskot Municipality", "KALIKOT"),
    ("Tilagufa Municipality", "KALIKOT"),
    ("Bhairabi Rural Municipality", "DAILEKH"),
    ("Mahabu Rural Municipality", "DAILEKH"),
    ("Gurans Rural Municipality", "DAILEKH"),
    ("Naumule Rural Municipality", "DAILEKH"),
    ("Bhagawatimai Rural Municipality", "DAILEKH"),
    ("Thantikandh Rural Municipality", "DAILEKH"),
    ("Dungeshwor Rural Municipality", "DAILEKH"),
    ("Aathabis Municipality", "DAILEKH"),
    ("Dullu Municipality", "DAILEKH"),
    ("Chamunda Bindrasaini Municipality", "DAILEKH"),
    ("Narayan Municipality", "DAILEKH"),
    ("Kuse Rural Municipality", "JAJARKOT"),
    ("Shiwalaya Rural Municipality", "JAJARKOT"),
    ("Barekot Rural Municipality", "JAJARKOT"),
    ("Junichande Rural Municipality", "JAJARKOT"),
    ("Nalagad Municipality", "JAJARKOT"),
    ("Bheri Municipality", "JAJARKOT"),
    ("Chhedagad Municipality", "JAJARKOT"),
    ("Kumakh Rural Municipality", "SALYAN"),
    ("Darma Rural Municipality", "SALYAN"),
    ("Kapurkot Rural Municipality", "SALYAN"),
    ("Kalimati Rural Municipality", "SALYAN"),
    ("Tribeni Rural Municipality Salyan", "SALYAN"),
    ("Chhatreshwori Rural Municipality", "SALYAN"),
    ("Siddha Kumakh Rural Municipality", "SALYAN"),
    ("Sharada Municipality", "SALYAN"),
    ("Bangad Kupinde Municipality", "SALYAN"),
    ("Bagchaur Municipality", "SALYAN"),
    ("Chaukune Rural Municipality", "SURKHET"),
    ("Simta Rural Municipality", "SURKHET"),
    ("Chingad Rural Municipality", "SURKHET"),
    ("Barahtal Rural Municipality", "SURKHET"),
    ("Gurbhakot Municipality", "SURKHET"),
    ("Panchpuri Municipality", "SURKHET"),
    ("Bheriganga Municipality", "SURKHET"),
    ("Lekbeshi Municipality", "SURKHET"),
    ("Birendranagar Municipality", "SURKHET"),
    ("Gaumul Rural Municipality", "BAJURA"),
    ("Himali Rural Municipality", "BAJURA"),
    ("Jagannath Rural Municipality", "BAJURA"),
    ("Khaptad Chhededaha Rural Municipality", "BAJURA"),
    ("Swami Kartik Khaapar Rural Municipality", "BAJURA"),
    ("Badimalika Municipality", "BAJURA"),
    ("Tribeni Municipality", "BAJURA"),
    ("Budhiganga Municipality", "BAJURA"),
    ("Budhinanda Municipality", "BAJURA"),
    ("Masta Rural Municipality", "BAJHANG"),
    ("Thalara Rural Municipality", "BAJHANG"),
    ("Talkot Rural Municipality", "BAJHANG"),
    ("Surma Rural Municipality", "BAJHANG"),
    ("SaiPaal Rural Municipality", "BAJHANG"),
    ("Durgathali Rural Municipality", "BAJHANG"),
    ("Bithadchir Rural Municipality", "BAJHANG"),
    ("Kedarseu Rural Municipality", "BAJHANG"),
    ("Khaptadchhanna Rural Municipality", "BAJHANG"),
    ("Chabispathivera Rural Municipality", "BAJHANG"),
    ("JayaPrithivi Municipality", "BAJHANG"),
    ("Bungal Municipality", "BAJHANG"),
    ("Lekam Rural Municipality", "DARCHULA"),
    ("Naugad Rural Municipality", "DARCHULA"),
    ("Byas Rural Municipality", "DARCHULA"),
    ("Dunhu Rural Municipality", "DARCHULA"),
    ("Marma Rural Municipality", "DARCHULA"),
    ("Apihimal Rural Municipality", "DARCHULA"),
    ("Malikaarjun Rural Municipality", "DARCHULA"),
    ("Mahakali Municipality Darchula", "DARCHULA"),
    ("Shailyashikhar Municipality", "DARCHULA"),
    ("Sigas Rural Municipality", "BAITADI"),
    ("Shivanath Rural Municipality", "BAITADI"),
    ("Surnaya Rural Municipality", "BAITADI"),
    ("Dilasaini Rural Municipality", "BAITADI"),
    ("Pancheshwar Rural Municipality", "BAITADI"),
    ("Dogadakedar Rural Municipality", "BAITADI"),
    ("Melauli Municipality", "BAITADI"),
    ("Dasharathchanda Municipality", "BAITADI"),
    ("Purchaudi Municipality", "BAITADI"),
    ("Patan Municipality", "BAITADI"),
    ("Alital Rural Municipality", "DADELDHURA"),
    ("Ajaymeru Rural Municipality", "DADELDHURA"),
    ("Bhageshwar Rural Municipality", "DADELDHURA"),
    ("Nawadurga Rural Municipality", "DADELDHURA"),
    ("Ganayapdhura Rural Municipality", "DADELDHURA"),
    ("Amargadhi Municipality", "DADELDHURA"),
    ("Parashuram Municipality", "DADELDHURA"),
    ("Sayal Rural Municipality", "DOTI"),
    ("Adharsha Rural Municipality", "DOTI"),
    ("Jorayal Rural Municipality", "DOTI"),
    ("Badikedar Rural Municipality", "DOTI"),
    ("Purbichauki Rural Municipality", "DOTI"),
    ("K I Singh Rural Municipality", "DOTI"),
    ("Bogtan Foodsil Rural Municipality", "DOTI"),
    ("Dipayal Silgadi Municipality", "DOTI"),
    ("Shikhar Municipality", "DOTI"),
    ("Dhakari Rural Municipality", "ACHHAM"),
    ("Mellekh Rural Municipality", "ACHHAM"),
    ("Chaurpati Rural Municipality", "ACHHAM"),
    ("Ramaroshan Rural Municipality", "ACHHAM"),
    ("Turmakhad Rural Municipality", "ACHHAM"),
    ("Bannigadhi Jayagadh Rural Municipality", "ACHHAM"),
    ("Sanphebagar Municipality", "ACHHAM"),
    ("Mangalsen Municipality", "ACHHAM"),
    ("Kamalbazar Municipality", "ACHHAM"),
    ("Panchadewal Binayak Municipality", "ACHHAM"),
    ("Chure Rural Municipality", "KAILALI"),
    ("Janaki Rural Municipality", "KAILALI"),
    ("Kailari Rural Municipality", "KAILALI"),
    ("Joshipur Rural Municipality", "KAILALI"),
    ("Mohanyal Rural Municipality", "KAILALI"),
    ("Bardagoriya Rural Municipality", "KAILALI"),
    ("Tikapur Municipality", "KAILALI"),
    ("Ghodaghodi Municipality", "KAILALI"),
    ("Bhajani Municipality", "KAILALI"),
    ("Gauriganga Municipality", "KAILALI"),
    ("Godawari Municipality Kailali", "KAILALI"),
    ("Lamkichuha Municipality", "KAILALI"),
    ("Beldandi Rural Municipality", "KANCHANPUR"),
    ("Laljhadi Rural Municipality", "KANCHANPUR"),
    ("Punarbas Municipality", "KANCHANPUR"),
    ("Krishnapur Municipality", "KANCHANPUR"),
    ("Mahakali Municipality Kanchanpur", "KANCHANPUR"),
    ("Bedkot Municipality", "KANCHANPUR"),
    ("Belauri Municipality", "KANCHANPUR"),
    ("Bhimdatta Municipality", "KANCHANPUR"),
)
