# Generated by Django 3.1.8 on 2021-06-28 17:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utilities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(max_length=10000)),
                ('video_url', models.URLField(blank=True, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.CharField(help_text='Separate more with a comma', max_length=255)),
                ('emails', models.CharField(help_text='Separate more with a comma', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=244, unique=True)),
                ('message', models.TextField(max_length=1024, unique=True)),
                ('seen', models.BooleanField(default=False, editable=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='utilities.feedback')),
                ('writer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='my_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, unique=True)),
                ('description', models.TextField(max_length=1024, unique=True)),
                ('video_url', models.URLField(blank=True, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='my_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=64, null=True)),
                ('content', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=utilities.models.upload_showcase_gallery_image_to)),
            ],
            options={
                'verbose_name': 'Showcase Gallery',
                'verbose_name_plural': 'Showcase Gallery',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utilities.models.upload_showcase_slider_image_to)),
                ('title', models.TextField(blank=True, max_length=512, null=True)),
                ('context', models.TextField(blank=True, max_length=512, null=True)),
                ('subtitle', models.TextField(blank=True, max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Showcase Slider',
                'verbose_name_plural': 'Showcase Slider',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utilities.models.upload_services_images_to)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='utilities.service')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='File to upload with feedback. Can be image, video, pdf, documents or zip files.', unique=True, upload_to=utilities.models.upload_feedback_file_to, validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv', 'png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG', 'pdf', 'docx', 'txt', 'zip'])])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='utilities.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utilities.models.upload_about_us_images_to)),
                ('content', models.CharField(blank=True, max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='utilities.aboutus')),
            ],
            options={
                'verbose_name': 'About Us Image',
                'verbose_name_plural': 'About Us Images',
            },
        ),
    ]
