# Generated by Django 3.1.8 on 2021-05-14 17:19

from django.db import migrations, models

import utilities.models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_us", models.TextField(max_length=10000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AboutUsImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="",
                        verbose_name=utilities.models.upload_about_us_images_to,
                    ),
                ),
            ],
        ),
    ]
