# Generated by Django 3.1.8 on 2021-06-27 12:34

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utilities.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=244)),
                ('message', models.TextField(max_length=1024)),
                ('seen', models.BooleanField(default=False, editable=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='utilities.feedback')),
                ('writer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='my_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to=utilities.models.upload_feedback_file_to, validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv', 'png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG', 'pdf', 'docx', 'txt', 'zip'])], verbose_name='File to upload with feedback. Can be image, video, pdf, documents or zip files.')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='utilities.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utilities.models.upload_services_images_to)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShowcaseGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=64, null=True)),
                ('content', models.CharField(blank=True, max_length=512, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=utilities.models.upload_showcase_gallery_image_to)),
            ],
            options={
                'verbose_name': 'Showcase Gallery',
                'verbose_name_plural': 'Showcase Gallery',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ShowcaseGallery',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='sliderimage',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='video_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(unique=True), blank=True, null=True, size=3),
        ),
        migrations.AddField(
            model_name='aboutusimage',
            name='content',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aboutusimage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='video_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(unique=True), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='aboutusimage',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='utilities.aboutus'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='utilities.service'),
        ),
    ]
