# Generated by Django 3.1.8 on 2021-06-27 12:43

import django.core.validators
from django.db import migrations, models
import utilities.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_auto_20210627_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=244, unique=True),
        ),
        migrations.AlterField(
            model_name='feedbackfile',
            name='file',
            field=models.FileField(help_text='File to upload with feedback. Can be image, video, pdf, documents or zip files.', unique=True, upload_to=utilities.models.upload_feedback_file_to, validators=[django.core.validators.FileExtensionValidator(['webm', 'mp4', 'mpeg', 'flv', 'png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG', 'pdf', 'docx', 'txt', 'zip'])]),
        ),
    ]
