# Generated by Django 3.1.8 on 2021-05-14 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_aboutus_aboutusimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutusimage",
            name="about_us",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about_us_images",
                to="utilities.aboutus",
            ),
            preserve_default=False,
        ),
    ]
