# Generated by Django 3.1.8 on 2021-06-27 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0003_auto_20210627_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='service',
            name='writer',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='my_services', to='auth.user'),
            preserve_default=False,
        ),
    ]
