# Generated by Django 3.1.8 on 2021-05-14 17:26

from django.db import migrations, models

import utilities.models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0003_aboutusimage_about_us"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "About Us", "verbose_name_plural": "About Us"},
        ),
        migrations.AlterField(
            model_name="aboutusimage",
            name="image",
            field=models.ImageField(
                upload_to=utilities.models.upload_about_us_images_to
            ),
        ),
    ]
