# Generated by Django 3.1.8 on 2021-05-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_auto_20210514_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusimage',
            options={'verbose_name': 'About Us Image', 'verbose_name_plural': 'About Us Images'},
        ),
    ]
