# Generated by Django 3.1.8 on 2021-06-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_auto_20210627_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='video_urls',
        ),
        migrations.RemoveField(
            model_name='service',
            name='video_urls',
        ),
    ]
