# Generated by Django 3.1.8 on 2021-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_auto_20210627_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='video_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='video_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
