# Generated by Django 3.1.8 on 2021-06-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_auto_20210627_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.CharField(help_text='Separate more with a comma', max_length=255)),
                ('emails', models.CharField(help_text='Separate more with a comma', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
