# Generated by Django 3.1 on 2020-08-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200826_2217'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='BranchProvince', to='accounts.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='BranchCountry', to='accounts.country'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='BranchDistrict', to='accounts.district'),
        ),
    ]
