# Generated by Django 3.1.8 on 2021-05-22 13:16

import branch.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='image',
        ),
        migrations.AddField(
            model_name='branch',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=branch.models.upload_branch_cover_image, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'bmp', 'tiff', 'JPG'])]),
        ),
    ]
