# Generated by Django 3.1.8 on 2021-06-28 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-timestamp'], 'permissions': [('approve_branch', 'Can toggle approval status of branch')], 'verbose_name_plural': 'Branches'},
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='updated_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='branch',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_approved_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='location.country'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='location.district'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is Main Branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='location.municipality'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='municipality_ward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='location.municipalityward'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='location.province'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='slogan',
            field=models.TextField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_updated_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='vdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='location.vdc'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='vdc_ward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='location.vdcward'),
        ),
    ]
