# Generated by Django 3.1.8 on 2021-05-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="approved_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="is_approved",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
