# Generated by Django 3.1 on 2020-09-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('location', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='BranchMunicipality', to='location.municipality'),
        ),
        migrations.AddField(
            model_name='branch',
            name='municipality_ward_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='BranchMunicipalityWardNo', to='location.municipalitywardnumber'),
        ),
        migrations.AddField(
            model_name='branch',
            name='vdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='BranchVdc', to='location.vdc'),
        ),
        migrations.AddField(
            model_name='branch',
            name='vdc_ward_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='BranchVdcWardNo', to='location.vdcwardnumber'),
        ),
    ]
