# Generated by Django 3.1 on 2020-08-17 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_admin',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='member',
            name='state',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='member',
            name='approved_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=512, unique=True)),
                ('country', models.CharField(choices=[('AFG', 'Afghanistan'), ('IND', 'India'), ('PAK', 'Pakistan'), ('BAN', 'Bangladesh'), ('SRI', 'Sri Lanka'), ('NEP', 'Nepal'), ('BHU', 'Bhutan'), ('MAL', 'Maldives')], max_length=3)),
                ('district', models.CharField(choices=[('BHOJPUR', 'Bhojpur'), ('DHANKUTA', 'Dhankuta'), ('ILAM', 'Ilam'), ('JHAPA', 'Jhapa'), ('KHOTANG', 'Khotang'), ('MORANG', 'Morang'), ('OKHALDHUNGA', 'Okhaldhunga'), ('PANCHTHAR', 'Panchthar'), ('SANKHUWASABHA', 'Sankhuwasabha'), ('SOLUKHUMBU', 'Solukhumbu'), ('SUNSARI', 'Sunsari'), ('TAPLEJUNG', 'Taplejung'), ('TERATHUM', 'Terhathum'), ('UDAYAPUR', 'Udayapur'), ('BARA', 'Bara'), ('PARSA', 'Parsa'), ('DHANUSHA', 'Dhanusha'), ('MAHOTTARI', 'Mahottari'), ('RAUTAHAT', 'Rautahat'), ('SAPTARI', 'Saptari'), ('SARLAHI', 'Sarlahi'), ('SIRAHA', 'Siraha'), ('BHAKTAPUR', 'Bhaktapur'), ('CHITWAN', 'Chitwan'), ('DHADING', 'Dhading'), ('DOLAKHA', 'Dolakha'), ('KATHMANDU', 'Kathmandu'), ('KAVREPALANCHOK', 'Kavrepalanchok'), ('LALITPUR', 'Lalitpur'), ('MAKWANPUR', 'Makwanpur'), ('NUWAKOT', 'Nuwakot'), ('RAMECHHAP', 'Ramechhap'), ('RASUWA', 'Rasuwa'), ('SINDHULI', 'Sindhuli'), ('SINDHUPALCHOK', 'Sindhupalchok'), ('BAGLUNG', 'Baglung'), ('GORKHA', 'Gorkha'), ('KASKI', 'Kaski'), ('LAMJUNG', 'Lamjung'), ('MANANG', 'Manang'), ('MUSTANG', 'Mustang'), ('MYAGDI', 'Myagdi'), ('NAWALPUR', 'Nawalpur'), ('PARBAT', 'Parbat'), ('SYANGJA', 'Syangja'), ('TANAHUN', 'Tanahun'), ('ARGHAKHACHI', 'Arghakhanchi'), ('BANKE', 'Banke'), ('BARDIYA', 'Bardiya'), ('DANG', 'Dang'), ('RUKUM', 'Rukum'), ('GULMI', 'Gulmi'), ('KAPILAVASTU', 'Kapilavastu'), ('PARASI', 'Parasi'), ('PALPA', 'Palpa'), ('PYUTHAN', 'Pyuthan'), ('ROLPA', 'Rolpa'), ('RUPANDEHI', 'Rupandehi'), ('DAILEKH', 'Dailekh'), ('DOLPA', 'Dolpa'), ('HUMLA', 'Humla'), ('JAJARKOT', 'Jajarkot'), ('JUMLA', 'Jumla'), ('KALIKOT', 'Kalikot'), ('MUGU', 'Mugu'), ('SALYAN', 'Salyan'), ('SURKHET', 'Surkhet'), ('RUKUM', 'Rukum'), ('ACHHAM', 'Achham'), ('BAITADI', 'Baitadi'), ('BAJHANG', 'Bajhang'), ('BAJURA', 'Bajura'), ('DADELDHURA', 'Dadeldhura'), ('DARCHULA', 'Darchula'), ('DOTI', 'Doti'), ('KAILALI', 'Kailali'), ('KANCHANPUR', 'Kanchanpur')], max_length=14, unique=True)),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('is_main', models.BooleanField(default=False, verbose_name='Is Main Branch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
