# Generated by Django 3.1.8 on 2021-06-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('branch', '0002_auto_20210629_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='location.country'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='location.district'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branches', to='location.province'),
        ),
    ]
