# Generated by Django 3.1 on 2020-09-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('branch', '0002_auto_20200907_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(default=0, upload_to='branch'),
            preserve_default=False,
        ),
    ]
