# Generated by Django 3.1.1 on 2020-09-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_auto_20200912_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='municipality_ward_no',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='vdc_ward_no',
        ),
    ]
